import './globals.css'
import type { Metadata } from 'next'
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import { Playfair_Display } from "next/font/google";

import initTranslations from "../i18n";
import NavBar from "@/components/home/NavBar";
import TranslationsProvider from "@/components/TranslationsProvider";

const myFont = Playfair_Display({
  subsets: ["latin"],
  weight: "400", 
  display: "swap",
  variable: "--my-font-family",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)} data-theme="winter">
      <body className={`${myFont.className} bg-background`}>
        <div>
          <NavBarWithTranslation params={{ locale }} />
          {children}
        </div>
      </body>
    </html>
  );
}


const i18nNamespaces = ["home", "common"];

async function NavBarWithTranslation({ params: { locale } }: any) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
      <NavBar />
    </TranslationsProvider>
  );
}